language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - make coverage
after_success:
  - coveralls
