# Generated by Django 3.0.6 on 2022-03-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_fields', '0002_auto_20160209_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedfieldmodification',
            name='field',
            field=models.CharField(editable=False, max_length=250, verbose_name='Field'),
        ),
    ]
